mode: local
iterations: 10
confidence: 0.95
programs:
    mmul:
      arguments: ''
    delannoy:
      arguments: '12'
    nbody:
      arguments: ''
    filegen:
      arguments: '15 15 1024000 1048576'
    filesearch:
      arguments: ''
    qap:
      arguments: 'problems/chr15a.dat'